### ISSUE TITLE
Use SQL with Clojure to insert prices into XTDB as a pricing and reporting service

### ISSUE THREAD

**Issue by refset** [xtdb/traderX#2]
Work is happening in https://github.com/xtdb/traderX/tree/demo2

**Comment by refset** [comment]
We've decided to entirely replace the reference data service with an XTDB-backed service which will handle pricing and reporting requirements also.

The existing trade service will be extended to accept a price, and will also POST the trade to the new reference service after submitting to its own H2 database (in practice a production system would more likely use Debezium to control the flow of change data).

**Comment by mpisanko** [comment]
now that i've dug deeper - there's a socket.io 'pub-sub' service - which basically get's trades published to and then processed. so should be ok to plug into that. same thing - different mechanics
